---
# tasks file for roles/deploy_py_logger
- name: Install Python 3.12
  ansible.windows.win_package:
    path: https://python.org
    product_id: 'Python 3.12.0 (64-bit)'
    arguments: /quiet InstallAllUsers=1 PrependPath=1
    state: present
- name: Install Python libraries 
  ansible.windows.win_shell: pip install requests watchdog discord-webhook 

- name: Copy logger file
  ansible.windows.win_copy:
    src: C:\Users\ericd\simple_powershell_logger\simple-powershell_logger\src\simple_powershell_logger\read_powershell_history.py
    dest: "{{logger_install_path}}"

- name: Execute Logger in background
  ansible.windows.win_shell: pythonw.exe {{logger_install_path}}
  async: 3600
  poll: 0 



