---
# defaults file for roles/deploy_py_logger
logger_install_path : 'C:\WINDOWS\system32\read_powershell_history.py'
exe_install_path : 'C:\WINDOWS\system32\read_powershell_history.exe'
task_name : 'history_log_service'
service_display_name: 'history_log_service'
task_description: 'logs history'
